---
title: "Data Manipulation"
output: giithub_document
---

```{r}
library(tidyverse)
```

Import FAS litters and pubs

```{r}
litters_df = read.csv("~/Desktop/desktop/Columbia 2023 Fall/Data Science/wrangling/data/FAS_litters.csv")
litters_df = janitor:: clean_names(litters_df)

pups_df = read.csv("~/Desktop/desktop/Columbia 2023 Fall/Data Science/wrangling/data/FAS_pups.csv")
pups_df = janitor:: clean_names(pups_df)

```

## `select` is used to select columns

```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group, gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, -starts_with("gd"))

select(litters_df, group, litter_id = litter_number)

select(litters_df, group, litter_id = litter_number, everything()) #这个everything function就是保留所有其他列

select(litters_df, gd0_weight, everything())


```

`select` vs `oull`
```{r}
select(litters_df, group) #S elect returns one or more columns as a data
pull(litters_df, group) # Pull returns a single column as a vector; 
```

```{r}
rename(litters_df, litter_id = litter_number)

relocate(litters_df, litter_number)
```



```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

get rid of rows using `filter()`

```{r}
filter(litters_df, group == "Con7") # = 就是等于，==是看TRUE or FALSE的

filter(litters_df,group == "Mod8")

filter(litters_df, group != "Con7") # != 是不等于

filter(litters_df,gd0_weight >20)

filter(litters_df, gd0_weight <=20)

filter(litters_df, group == "Con7" | group =="Con8") # |这个是指or

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"), gd0_weight >20)
```

what about missiong rows

```{r}
drop_na(litters_df)
```

## `Mutate`

this is used to add or change variables.

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate (litters_df, group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```


## `arange`

```{r}
arrange(litters_df,gd0_weight)
arrange(litters_df,group, gd0_weight)

```



## pipes

```{r}
litters_df = 
  read_csv("~/Desktop/desktop/Columbia 2023 Fall/Data Science/wrangling/data/FAS_litters.csv") |>
  janitor::clean_names()|>
  select(-starts_with("pups"))|>
  mutate(
    grou = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight,
  )|>
  drop_na(wt_gain)|>
  arrange(group,wt_gain)
```

`这个|>就是then的意思`



