---
title: "wrangling"
output: github_document
date: "2023-09-19"
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

lets's import the `Fas litters.csv` csv.

```{r}
litters_df = 
  read_csv("~/Desktop/wrangling/data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)
```

Import the same dataset using an absolute path


```{r}
pups_df = read_csv("~/Desktop/wrangling/data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)
```

#look at data
```{r}
litters_df

head(litters_df)

tail(litters_df)
```
You can use `view`
```{r, eval = FALSE}
view(litters_df)
```

look at a data summary
```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df=
  read_csv("~/Desktop/wrangling/data/FAS_litters.csv", skip = 10, col_names = FALSE)

```


```{r}
litters_df=
  read_csv("~/Desktop/wrangling/data/FAS_litters.csv", na = c("NA", 19, "."))

```

Column types


```{r}

litters_df=
  read_csv("~/Desktop/wrangling/data/FAS_litters.csv", 
           col_types = 
             cols(
               `GD0 weight` = col_character()
             )
           )

```


Import a xlsx file first

```{r}
mlb_df = 
  read_excel("~/Desktop/wrangling/data/mlb11.xlsx")
```

Import a SAS file

```{r}
pulse_df = 
  read_sas("~/Desktop/wrangling/data/public_pulse_data.sas7bdat")
```

